CREATE DATABASE NETFLIX_DB;
USE NETFLIX_DB;
SHOW TABLES;

-- CREATING THE TABLE STRUCTURE BASED ON THE DATASET
CREATE TABLE IF NOT EXISTS NETFLIX_DATA
(
SHOW_ID INT,
TITLE VARCHAR(150),
DIRECTOR VARCHAR(200),
CAST TEXT,
COUNTRY VARCHAR(150),
DATE_ADDED VARCHAR(30),
RELEASED_YEAR VARCHAR(10),
RATING VARCHAR(10),
DURATION VARCHAR(20),
CATEGORY_OF_MOVIE TEXT,
DESCRIPTION_OF_MOVIE TEXT,
TYPE_OF_SHOW VARCHAR(100)
);

LOAD DATA INFILE 'C:/Users/hp/OneDrive/Documents/NETFLIX/netflix_titles_nov_2019.csv' INTO TABLE NETFLIX_DATA
FIELDS TERMINATED BY ','
enclosed by '"'
lines terminated by '\r\n'
IGNORE 1 ROWS;
SHOW TABLES;
DESC NETFLIX_DATASET;

DROP TABLE NETFLIX_DATASET;
SELECT * FROM NETFLIX_DATA;
ALTER TABLE NETFLIX_DATA
MODIFY COLUMN RELEASED_YEAR VARCHAR(20);
ALTER TABLE NETFLIX_DATA
MODIFY COLUMN TYPE_OF_SHOW VARCHAR(200);

SELECT count(*) FROM NETFLIX_DATA;
SELECT COUNT(*) AS CONTENT_COUNT FROM NETFLIX_DATA;
SELECT TITLE, TYPE_OF_SHOW FROM NETFLIX_DATA;

-- 1. COUNT THE NUMBER OF MOVIES AND TV SHOWS
SELECT TYPE_OF_SHOW,
COUNT(*) AS CONTENT_COUNT
FROM NETFLIX_DATA
GROUP BY TYPE_OF_SHOW;

-- 2. FIND TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFLIX
SELECT COUNTRY, COUNT(*) AS CONTENT_COUNT
FROM NETFLIX_DATA
GROUP BY COUNTRY
ORDER BY CONTENT_COUNT DESC
LIMIT 5;

-- LIST ALL THE MOVIES THAT ARE DOCUMENTARIES
SELECT TITLE FROM NETFLIX_DATA WHERE TYPE_OF_SHOW LIKE 'Movie%' AND CATEGORY_OF_MOVIE LIKE '%Documentaries%';

-- 4. IDENTIFY THE LONGEST MOVIE
SELECT CAST(REPLACE(DURATION, 'min', '') AS UNSIGNED) C, TYPE_OF_SHOW, TITLE FROM NETFLIX_DATA WHERE TYPE_OF_SHOW LIKE 'Movie%'
ORDER BY C DESC LIMIT 1;
 
SELECT TITLE, DURATION, TYPE_OF_SHOW FROM NETFLIX_DATA
WHERE TYPE_OF_SHOW LIKE 'Movie%'
ORDER BY CAST(REPLACE(DURATION, 'min', '') AS UNSIGNED) DESC
LIMIT 1;

-- 5. COUNT THE NUMBER OF CONTENT ITEM IN EACH GENRE
SELECT CATEGORY_OF_MOVIE,
COUNT(*) AS CONTENT_COUNT
FROM NETFLIX_DATA
GROUP BY 1
ORDER BY CONTENT_COUNT DESC;

-- 6. LIST ALL THE MOVIES RELEASED IN A SPECIFIC YEAR (e.g 2019)
SELECT TITLE, TYPE_OF_SHOW FROM NETFLIX_DATA WHERE TYPE_OF_SHOW LIKE 'Movie%' AND RELEASED_YEAR = 2019;

-- 7. FIND CONTENT ADDED IN THE LAST 6 YEARS
      SELECT 
    title,
    YEAR(STR_TO_DATE(TRIM(date_added), '%M %d, %Y')) AS added_year
FROM netflix_data
WHERE YEAR(CURDATE()) 
      - YEAR(STR_TO_DATE(TRIM(date_added), '%M %d, %Y')) <= 6;
      SELECT 
    title,
    YEAR(STR_TO_DATE(TRIM(date_added), '%M %d, %Y')) AS added_year
FROM netflix_data
WHERE STR_TO_DATE(TRIM(date_added), '%M %d, %Y') >=
(
    SELECT DATE_SUB(
        MAX(STR_TO_DATE(TRIM(date_added), '%M %d, %Y')),
        INTERVAL 6 YEAR
    )
    FROM netflix_data
);

-- 8. FIND ALL THE MOVIES AND TV SHOWS BY DIRECTOR RAJIV CHILAKA
SELECT * FROM NETFLIX_DATA
WHERE DIRECTOR = 'RAJIV CHILAKA';

-- 9. LIST ALL THE TV SHOWS WITH MORE THAN 5 SEASONS
SELECT TITLE, DURATION
FROM NETFLIX_DATA
WHERE TYPE_OF_SHOW LIKE '%TV Show%' AND CAST(REPLACE(DURATION, 'Sesaon', '') AS UNSIGNED) > 5;

-- 10. FIND ALL THE CONTENT WITHOUT A DIRECTOR
SELECT * FROM NETFLIX_DATA WHERE DIRECTOR IS NULL OR DIRECTOR = '';

-- 11. FIND HOW MANY MOVIES SALMAN KHAN RELEASED IN LAST 10 YEAR
SELECT COUNT(*) AS movie_count
FROM netflix_data
WHERE type_of_show = 'Movie'
  AND `cast` LIKE '%Salman Khan%'
  AND released_year >= (
      SELECT MAX(released_year) - 10
      FROM netflix_data
  );

-- 12. IDENTIFY MOVIES/TV SHOWS FEATURING A SPECIFIC ACTOR (e.g "ROBERT DE NIRO")
SELECT TITLE, TYPE_OF_SHOW, CAST
FROM NETFLIX_DATA
WHERE CAST LIKE '%Robert de Niro%';

-- 13. GROUP THE RECORDS BY YEAR AND COUNT THE NUMBER OF MOVIES/TV SHOWS ADDED EACH YEAR
SELECT RELEASED_YEAR, COUNT(*) AS CONTENT_COUNT
FROM NETFLIX_DATA
GROUP BY RELEASED_YEAR
ORDER BY RELEASED_YEAR DESC;

-- 14. FIND EACH YEAR AND AVERAGE NUMBERS OF CONTENT RELEASED IN INDIA ON NETFLIX
SELECT RELEASED_YEAR, AVG(CONTENT_COUNT)
FROM
(SELECT RELEASED_YEAR, COUNT(*) AS CONTENT_COUNT
FROM NETFLIX_DATA
WHERE COUNTRY = 'INDIA'
GROUP BY RELEASED_YEAR
ORDER BY RELEASED_YEAR DESC) AS YEAR_DATA
GROUP BY RELEASED_YEAR;

-- 15. IDENTIFY THE TOP 3 MOST COMMON GENRE IN THE DATASET
SELECT CATEGORY_OF_MOVIE, COUNT(*) AS CONTENT_COUNT
FROM NETFLIX_DATA
GROUP BY CATEGORY_OF_MOVIE
ORDER BY CONTENT_COUNT DESC
LIMIT 3;

-- 16. IDENTIFY THE MOST ACTIVE MONTH FOR ADDING MOVIES/TV SHOWS (BY COUNT)
SELECT * FROM
(SELECT MONTH(str_to_date(DATE_ADDED, '%M%d, %Y')) AS MONTH, COUNT(*) AS COUNT_CONTENT
FROM NETFLIX_DATA
GROUP BY month
ORDER BY COUNT_CONTENT DESC) AS RESULT_DATA
WHERE MONTH IS NOT NULL
LIMIT 1;

-- 17. COMPARE THE NUMBER OF MOVIES AND TV SHOWS ADDED BEFORE AND AFTER 2015
SELECT
 CASE WHEN RELEASED_YEAR < 2015 THEN 'BEFORE 2015' ELSE 'AFTER 2015' END AS PERIOD,
 TYPE_OF_SHOW,
 COUNT(*) AS COUNT
FROM NETFLIX_DATA
GROUP BY PERIOD, TYPE_OF_SHOW;

-- 18. RETRIEVE ALL MOVIES /TV SHOWS THAT WERE ADDED IN THE LAST 6 MONTHS
SELECT * FROM NETFLIX_DATA
WHERE str_to_date(DATE_ADDED, '%M %d, %Y') >= date_sub(curdate(), INTERVAL 6 MONTH);

SELECT *
FROM netflix_data
WHERE STR_TO_DATE(TRIM(date_added), '%M %d, %Y') >=
(
    SELECT DATE_SUB(
        MAX(STR_TO_DATE(TRIM(date_added), '%M %d, %Y')),
        INTERVAL 6 MONTH
    )
    FROM netflix_data
);

-- 19. FIND THE AVERAGE DURATION OF MOVIES (IN MINUTES)
SELECT AVG(CAST(REPLACE(DURATION, 'min', '') AS UNSIGNED)) FROM NETFLIX_DATA
WHERE TYPE_OF_SHOW LIKE '%Movie%';

-- 20. FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN INDIA
SELECT CAST, COUNT(TYPE_OF_SHOW) AS COUNT_MOVIE
FROM NETFLIX_DATA
WHERE TYPE_OF_SHOW LIKE '%Movie%' AND COUNTRY = 'INDIA'
GROUP BY CAST
ORDER BY COUNT_MOVIE DESC
LIMIT 10;

-- 21. CATEGORIZE CONTENT BASED ON THE PRESENCE OF 'KILL' AND 'VOILENCE' KEYWORD
SELECT *,
 CASE
    WHEN (DESCRIPTION_OF_MOVIE) LIKE '%kill%' AND (DESCRIPTION_OF_MOVIE) LIKE '%violence%' THEN 'Kill and Violence'
    WHEN (DESCRIPTION_OF_MOVIE) LIKE '%kill%' THEN 'Kill'
    WHEN (DESCRIPTION_OF_MOVIE) LIKE '%violence%' THEN 'Violence'
    ELSE 'Normal'
  END AS content_category
FROM NETFLIX_DATA;